### ISSUE TITLE
Publish v0.2.0

### ISSUE THREAD

**Issue by ghost** [sambeevors/tailwindcss-neumorphism#12]
Hi Sam,

Thank you for the plugin!

Would you mind publishing v0.2.0 to NPM?

Best regards

**Comment by sambeevors** [comment]
Hey!

I totally forgot about this project after I got locked out of my npm account - but I just published it under a new npm package -> https://github.com/sambeevors/tailwindcss-neumorphism/commit/422720956b77d121ec1f3c69bbcaf73435cc999c
